{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fkk.plugin",
    "module": "tracker-plugin",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tracker-plugin-1.0.11.jar",
          "url": "tracker-plugin-1.0.11.jar",
          "size": 13669,
          "sha512": "c27c32ce5b85607795f89d2ce176199e06cc9a1b4b201adfed97df9ead7d164ac4278f18f0b66258f28c7379486cfda0341150e92115efbac818d704ddac3f0b",
          "sha256": "bfde0a02246df730c7ce8df9cb670994c9fb47f185b9c7d3848385900e8c3b45",
          "sha1": "4f4445fe67f92e57924ec60b034b09046550ff15",
          "md5": "96c0d51c0135b5bc2e1e58a7a0e0d7c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-plugin-1.0.11.jar",
          "url": "tracker-plugin-1.0.11.jar",
          "size": 13669,
          "sha512": "c27c32ce5b85607795f89d2ce176199e06cc9a1b4b201adfed97df9ead7d164ac4278f18f0b66258f28c7379486cfda0341150e92115efbac818d704ddac3f0b",
          "sha256": "bfde0a02246df730c7ce8df9cb670994c9fb47f185b9c7d3848385900e8c3b45",
          "sha1": "4f4445fe67f92e57924ec60b034b09046550ff15",
          "md5": "96c0d51c0135b5bc2e1e58a7a0e0d7c3"
        }
      ]
    }
  ]
}
