{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fkk.plugin",
    "module": "tracker-plugin",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tracker-plugin-1.0.10.jar",
          "url": "tracker-plugin-1.0.10.jar",
          "size": 13762,
          "sha512": "65d9930f612783912e1b95e5c9594befa455572228010afc718d56524afd8b551f717b52d2de65ef135119960845408f04ddee7e7b27368163a1eaad2e693a09",
          "sha256": "4ddbb6978c5571d45a2766631e4b6d31875c8dab6fdf4516f6cb3bce625886bf",
          "sha1": "e49f627a7f4b27fb5543c257ff7b490348bfb995",
          "md5": "52a35e2b8ab101e695227964dcde6975"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        }
      ],
      "files": [
        {
          "name": "tracker-plugin-1.0.10.jar",
          "url": "tracker-plugin-1.0.10.jar",
          "size": 13762,
          "sha512": "65d9930f612783912e1b95e5c9594befa455572228010afc718d56524afd8b551f717b52d2de65ef135119960845408f04ddee7e7b27368163a1eaad2e693a09",
          "sha256": "4ddbb6978c5571d45a2766631e4b6d31875c8dab6fdf4516f6cb3bce625886bf",
          "sha1": "e49f627a7f4b27fb5543c257ff7b490348bfb995",
          "md5": "52a35e2b8ab101e695227964dcde6975"
        }
      ]
    }
  ]
}
